# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crawling.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crawling.proto',
  package='crawling',
  syntax='proto3',
  serialized_options=b'\n\031io.grpc.crawling.crawlingB\rCrawlingProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63rawling.proto\x12\x08\x63rawling\",\n\x0cScrapRequest\x12\r\n\x05\x62oard\x18\x01 \x01(\t\x12\r\n\x05pages\x18\x02 \x01(\x05\"A\n\nScrapReply\x12\x12\n\nresultCode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03 \x01(\t2C\n\x08\x43rawling\x12\x37\n\x05Scrap\x12\x16.crawling.ScrapRequest\x1a\x14.crawling.ScrapReply\"\x00\x42\x32\n\x19io.grpc.crawling.crawlingB\rCrawlingProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_SCRAPREQUEST = _descriptor.Descriptor(
  name='ScrapRequest',
  full_name='crawling.ScrapRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='board', full_name='crawling.ScrapRequest.board', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pages', full_name='crawling.ScrapRequest.pages', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=72,
)


_SCRAPREPLY = _descriptor.Descriptor(
  name='ScrapReply',
  full_name='crawling.ScrapReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultCode', full_name='crawling.ScrapReply.resultCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='crawling.ScrapReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output', full_name='crawling.ScrapReply.output', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['ScrapRequest'] = _SCRAPREQUEST
DESCRIPTOR.message_types_by_name['ScrapReply'] = _SCRAPREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScrapRequest = _reflection.GeneratedProtocolMessageType('ScrapRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPREQUEST,
  '__module__' : 'crawling_pb2'
  # @@protoc_insertion_point(class_scope:crawling.ScrapRequest)
  })
_sym_db.RegisterMessage(ScrapRequest)

ScrapReply = _reflection.GeneratedProtocolMessageType('ScrapReply', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPREPLY,
  '__module__' : 'crawling_pb2'
  # @@protoc_insertion_point(class_scope:crawling.ScrapReply)
  })
_sym_db.RegisterMessage(ScrapReply)


DESCRIPTOR._options = None

_CRAWLING = _descriptor.ServiceDescriptor(
  name='Crawling',
  full_name='crawling.Crawling',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=141,
  serialized_end=208,
  methods=[
  _descriptor.MethodDescriptor(
    name='Scrap',
    full_name='crawling.Crawling.Scrap',
    index=0,
    containing_service=None,
    input_type=_SCRAPREQUEST,
    output_type=_SCRAPREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CRAWLING)

DESCRIPTOR.services_by_name['Crawling'] = _CRAWLING

# @@protoc_insertion_point(module_scope)
